# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-07 21:33
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100000)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('issue_no', models.IntegerField(primary_key=True, serialize=False)),
                ('object', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=100000)),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_no', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('leader', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('phase', models.IntegerField(choices=[(0, b'Communication'), (1, b'Planning'), (2, b'Modeling'), (3, b'Construction'), (4, b'Deploylment')], default=0)),
                ('description', models.CharField(max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('customer', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100000)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
                ('actual_end_date', models.DateField()),
                ('priority', models.IntegerField(choices=[(0, b'Required'), (1, b'Significant'), (2, b'Moderate'), (3, b'Minor'), (4, b'Low')], default=0)),
                ('description', models.CharField(max_length=100000)),
                ('project_affiliation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.Project')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('firstname', models.CharField(blank=True, max_length=50, null=True)),
                ('lastname', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.IntegerField(max_length=15)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='announcer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User', unique=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='issue_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Issue', unique=True),
        ),
        migrations.AddField(
            model_name='answer',
            name='replyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.User', unique=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
