# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue_detail',
            name='issue',
        ),
        migrations.RemoveField(
            model_name='issue_detail',
            name='replyer',
        ),
        migrations.DeleteModel(
            name='Issue_Detail',
        ),
    ]
